name: Continuous monitoring of distribution channels
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  pull-agent:
    name: Pull X-Ray .NET agent from S3
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pull X-Ray .NET agent from S3
        id: distribution-availability-s3
        run: |
          wget https://s3.amazonaws.com/aws-xray-assets.us-east-1/xray-agent-installer/aws-xray-dotnet-agent-installer-beta-X86.msi
          wget https://s3.amazonaws.com/aws-xray-assets.us-east-1/xray-agent-installer/aws-xray-dotnet-agent-installer-beta-X64.msi

      - name: Publish metric on X-Ray .NET agent distribution availability (S3)
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.distribution-availability-github.outcome }}" == "failure" ]]; then
            aws cloudwatch put-metric-data --metric-name XRayDotnetAgentS3DistributionUnavailability --dimensions failure=rate --namespace MonitorAgent --value 1 --timestamp $(date +%s)
          else
            aws cloudwatch put-metric-data --metric-name XRayDotnetAgentS3DistributionUnavailability --dimensions failure=rate --namespace MonitorAgent --value 0 --timestamp $(date +%s)
          fi
